services:
  congrapp.server:
    build:
      context: .
      dockerfile: "Congrapp.Server/Dockerfile"
      target: "base"
    entrypoint: 
      - "dotnet"
      - "./bin/Debug/net9.0/Congrapp.Server.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      ASPNETCORE_STATICWEBASSETS: "./bin/Debug/net9.0/Congrapp.Server.staticwebassets.runtime.CT.json"
    volumes:
      - "./Congrapp.Server:/app:rw"
      - ".:/src:rw"
      - "nuget-packages:/home/app/.nuget/packages"
    working_dir: "/app"

  congrapp.client:
    environment:
      - REACT_APP_API_BASE_URL=http://congrapp.server:8080
    volumes:
      - "./congrapp-client:/app:rw"
      - "/app/node_modules"

volumes:
  nuget-packages:
