services:
  congrapp.server:
    image: congrapp.server
    build:
      context: .
      dockerfile: Congrapp.Server/Dockerfile
      target: "base"
    entrypoint:
      - "dotnet"
      - "./bin/Debug/net9.0/Congrapp.Server.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      ASPNETCORE_STATICWEBASSETS: "./bin/Debug/net9.0/Congrapp.Server.staticwebassets.runtime.CT.json"
    volumes:
      - "./Congrapp.Server:/app:rw"
      - ".:/src:rw"
      - "nuget-packages:/home/app/.nuget/packages"
    working_dir: "/app"
    ports:
      - "8080:8080"
    depends_on:
      - congrapp.papercut
  
  congrapp.client:
    build:
      context: ./congrapp-client
      dockerfile: Dockerfile
    environment:
      - REACT_APP_API_BASE_URL=http://congrapp.server:8080
    volumes:
      - "./congrapp-client:/app:rw"
      - "/app/node_modules"
    ports:
      - "3000:80"
    depends_on:
      - congrapp.server
  
  congrapp.papercut:
    image: changemakerstudiosus/papercut-smtp:latest
    container_name: congrapp.papercut
    ports:
      - "8081:80"
      - "25:25"
    volumes:
      - papercut_data:/var/papercut
    environment:
      - PAPERCUT_SMTP_MESSAGESTORE=/var/papercut

volumes:
  papercut_data:
  nuget-packages:
