services:
  congrapp.server:
    image: congrapp.server
    build:
      context: .
      dockerfile: Congrapp.Server/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - congrapp.papercut
  
  congrapp.client:
    build:
      context: ./congrapp-client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - congrapp.server
  
  congrapp.papercut:
    image: changemakerstudiosus/papercut-smtp:latest
    container_name: congrapp.papercut
    ports:
      - "8081:80"
      - "25:25"
    volumes:
      - papercut_data:/var/papercut
    environment:
      - PAPERCUT_SMTP_MESSAGESTORE=/var/papercut

volumes:
  papercut_data:
